# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "google_authentication"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Fabio Napoleoni"]
  s.date = "2012-06-06"
  s.description = "Authenticate users through Google in your app using devise and omniauth"
  s.email = "f.napoleoni@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rvmrc",
    "CHANGES.markdown",
    "Gemfile",
    "Guardfile",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "app/controllers/google_authentication/omniauth_callbacks_controller.rb",
    "app/controllers/google_authentication/sessions_controller.rb",
    "config/routes.rb",
    "features/google_authentication.feature",
    "features/step_definitions/google_authentication_steps.rb",
    "features/support/env.rb",
    "google_authentication.gemspec",
    "lib/generators/google_authentication/google_authentication_generator.rb",
    "lib/generators/google_authentication/install_generator.rb",
    "lib/generators/templates/MODEL.warning",
    "lib/generators/templates/README",
    "lib/generators/templates/google_authentication.rb",
    "lib/generators/templates/migration.rb",
    "lib/google_authentication.rb",
    "lib/google_authentication/acts_as_google_user.rb",
    "lib/google_authentication/engine.rb",
    "spec/dummy/Rakefile",
    "spec/dummy/app/controllers/application_controller.rb",
    "spec/dummy/app/controllers/posts_controller.rb",
    "spec/dummy/app/helpers/application_helper.rb",
    "spec/dummy/app/helpers/posts_helper.rb",
    "spec/dummy/app/models/post.rb",
    "spec/dummy/app/models/user.rb",
    "spec/dummy/app/views/layouts/application.html.erb",
    "spec/dummy/app/views/posts/_form.html.erb",
    "spec/dummy/app/views/posts/edit.html.erb",
    "spec/dummy/app/views/posts/index.html.erb",
    "spec/dummy/app/views/posts/new.html.erb",
    "spec/dummy/app/views/posts/show.html.erb",
    "spec/dummy/config.ru",
    "spec/dummy/config/application.rb",
    "spec/dummy/config/boot.rb",
    "spec/dummy/config/database.yml",
    "spec/dummy/config/environment.rb",
    "spec/dummy/config/environments/development.rb",
    "spec/dummy/config/environments/production.rb",
    "spec/dummy/config/environments/test.rb",
    "spec/dummy/config/initializers/backtrace_silencers.rb",
    "spec/dummy/config/initializers/devise.rb",
    "spec/dummy/config/initializers/inflections.rb",
    "spec/dummy/config/initializers/mime_types.rb",
    "spec/dummy/config/initializers/secret_token.rb",
    "spec/dummy/config/initializers/session_store.rb",
    "spec/dummy/config/locales/devise.en.yml",
    "spec/dummy/config/locales/en.yml",
    "spec/dummy/config/routes.rb",
    "spec/dummy/db/migrate/20110630105039_create_posts.rb",
    "spec/dummy/db/migrate/20110630111038_devise_create_users.rb",
    "spec/dummy/db/schema.rb",
    "spec/dummy/public/404.html",
    "spec/dummy/public/422.html",
    "spec/dummy/public/500.html",
    "spec/dummy/public/favicon.ico",
    "spec/dummy/public/javascripts/application.js",
    "spec/dummy/public/javascripts/controls.js",
    "spec/dummy/public/javascripts/dragdrop.js",
    "spec/dummy/public/javascripts/effects.js",
    "spec/dummy/public/javascripts/prototype.js",
    "spec/dummy/public/javascripts/rails.js",
    "spec/dummy/public/stylesheets/.gitkeep",
    "spec/dummy/public/stylesheets/scaffold.css",
    "spec/dummy/script/rails",
    "spec/generators/google_authentication_generator_spec.rb",
    "spec/generators/install_generator_spec.rb",
    "spec/google_authentication_spec.rb",
    "spec/integration/navigation_spec.rb",
    "spec/models/acts_as_google_user_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/fabn/google_authentication"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Authenticate users through Google in your app"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.1.0"])
      s.add_runtime_dependency(%q<omniauth>, [">= 1.0"])
      s.add_runtime_dependency(%q<omniauth-google-apps>, [">= 0"])
      s.add_runtime_dependency(%q<devise>, [">= 2.0"])
      s.add_development_dependency(%q<sqlite3>, ["~> 1.3.5"])
      s.add_development_dependency(%q<rspec-rails>, [">= 2.9.0"])
      s.add_development_dependency(%q<shoulda-matchers>, [">= 0"])
      s.add_development_dependency(%q<generator_spec>, [">= 0.8.5"])
      s.add_development_dependency(%q<guard-rspec>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0.4.0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, ["~> 0.10"])
      s.add_development_dependency(%q<aruba>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.2"])
    else
      s.add_dependency(%q<rails>, [">= 3.1.0"])
      s.add_dependency(%q<omniauth>, [">= 1.0"])
      s.add_dependency(%q<omniauth-google-apps>, [">= 0"])
      s.add_dependency(%q<devise>, [">= 2.0"])
      s.add_dependency(%q<sqlite3>, ["~> 1.3.5"])
      s.add_dependency(%q<rspec-rails>, [">= 2.9.0"])
      s.add_dependency(%q<shoulda-matchers>, [">= 0"])
      s.add_dependency(%q<generator_spec>, [">= 0.8.5"])
      s.add_dependency(%q<guard-rspec>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0.4.0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<cucumber>, ["~> 0.10"])
      s.add_dependency(%q<aruba>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.1.0"])
    s.add_dependency(%q<omniauth>, [">= 1.0"])
    s.add_dependency(%q<omniauth-google-apps>, [">= 0"])
    s.add_dependency(%q<devise>, [">= 2.0"])
    s.add_dependency(%q<sqlite3>, ["~> 1.3.5"])
    s.add_dependency(%q<rspec-rails>, [">= 2.9.0"])
    s.add_dependency(%q<shoulda-matchers>, [">= 0"])
    s.add_dependency(%q<generator_spec>, [">= 0.8.5"])
    s.add_dependency(%q<guard-rspec>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0.4.0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<cucumber>, ["~> 0.10"])
    s.add_dependency(%q<aruba>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
  end
end

